version: "2"
checks:
  method-complexity:
    config:
      threshold: 10
  similar-code:
    config:
      threshold: 60
  identical-code:
    config:
      threshold: 60
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-58
    config:
      file: ".rubocop.yml"
    checks:
      #################### Lint ###########################
      Rubocop/Lint/AssignmentInCondition:
        enabled: false
      Rubocop/Lint/HandleExceptions:
        enabled: false
      Rubocop/Lint/UnusedBlockArgument:
        enabled: false
      Rubocop/Lint/ShadowingOuterLocalVariable:
        enabled: false
      #################### Metric ###########################
      Rubocop/Metrics/AbcSize:
        enabled: false
      Rubocop/Metrics/ClassLength:
        enabled: false
      Rubocop/Metrics/MethodLength:
        enabled: false
      Rubocop/Metrics/BlockLength:
        enabled: false
      #################### Style ###########################
      Rubocop/Style/FrozenStringLiteralComment:
        enabled: false
      Rubocop/Style/WordArray:
        enabled: false
      Rubocop/Style/Documentation:
        enabled: false
      Rubocop/Style/FormatStringToken:
        enabled: false
      #################### Layout ###########################
      Layout/TrailingBlankLines:
        enabled: true
      Layout/DotPosition:
        enabled: true
      Layout/IndentHash:
        enabled: true
      Layout/MultilineMethodCallIndentation:
        enabled: true
      Layout/MultilineAssignmentLayout:
        enabled: true
      Layout/AlignParameters:
        enabled: true
      Layout/EndAlignment:
        enabled: true

exclude_patterns:
  - "bundler.gemspec"
  - "*.md"
  - lib/bundler/ssl_certs/*.pem
  - lib/bundler/vendor/**/*
  - lib/bundler/templates/**/*.tt
  - man/*
  - vendor/**/*
  - db/**/*
  - tmp/**/*
  - bin/**/*
  - log/**/*
  - config/**/*
  - lib/tasks/**/*
  - app/assets/**/*
  - "Rakefile"
  - spec/spec_helper.rb
  - spec/cassettes/**/*
  - spec/support/**/*
  - spec/rails_helper.rb
  - micro-shared/**/*
  - "Gemfile"
  - "Gemfile.lock"
  - "Guardfile"
  - node_modules/**/*
