version: '3'
services:

  deendemy_db:
    container_name: deendemy_db
    hostname: deendemy_db
    image: mongo:4.0-xenial
    restart: always
    ports:
      - 27017:27017
    networks:
      - deendemy_main
    environment:
      - MONGO_INITDB_DATABASE=deendemy_development
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test

  deendemy_db_test:
    container_name: deendemy_db_test
    hostname: deendemy_db_test
    image: mongo:4.0-xenial
    restart: always
    ports:
      - 27019:27017
    networks:
      - deendemy_main
    environment:
      - MONGO_INITDB_DATABASE=deendemy_test
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
  
  deendemy_redis:
    container_name: deendemy_redis
    image: redis:4-alpine
    restart: always
    ports:
      - 6379
    networks:
      - deendemy_main
  
  deendemy_mailcatcher:
    container_name: deendemy_mailcatcher
    image: zolweb/docker-mailcatcher:latest
    ports:
    - 1025:1025
    - 1080:1080
    networks:
      - deendemy_main

  deendemy_api:
    container_name: deendemy_api
    restart: always
    build:
      context: .
      args:
        - APP_ENV=local
    volumes:
      - .:/deendemy
    networks:
      - deendemy_main
    ports:
      - 3000:3000
    expose:
      - 3000
      - 1025
      - 1080
    depends_on:
      - deendemy_db
      - deendemy_db_test
      - deendemy_redis
      - deendemy_mailcatcher
    environment:
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
      - MONGO_URI=mongodb://test:test@deendemy_db:27017/deendemy_development?authSource=admin
      - SENTRY_DSN=https://03aeb5d40eac47f5888d53fa9eb586da:d488e9275c624915b6a8569b422858ca@o375539.ingest.sentry.io/5195164
      - REDIS_URL=redis://deendemy_redis:6379/12
      - SECRET_KEY_BASE=4d1d49d3e373fedf445ada72f1db345c
      - RAILS_MASTER_KEY=4d1d49d3e373fedf445ada72f1db345c
      - APPLICATION_HOST=http://0.0.0.0:3000

  # Elastic Search
  # deendemy_els:
  #   container_name: deendemy_els

networks:
  deendemy_main:
    driver: bridge
