default: &default
  adapter: redis
  channel_prefix: deendemy
  url: <%= ENV.fetch('REDIS_URL') { 'redis://localhost:6379/1' } %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
