development:
  clients:
    default:
      # uri: mongodb://deendemy_db:27017
      database: deendemy_development
      hosts:
          - deendemy_db:27017
          - 127.0.0.1:27017
      options:
        user: test
        password: test
        server_selection_timeout: 5
        # ssl: true
  options:
    app_name: DeendemyAPI

test:
  clients:
    default:
      # uri: mongodb://deendemy_db:27017
      database: deendemy_test
      hosts:
          - deendemy_db:27017
          - 127.0.0.1:27017
      options:
        user: test
        password: test
        read:
          mode: :primary
        max_pool_size: 1
  options:
    app_name: DeendemyTestAPI
