development:
  clients:
    default:
      database: deendemy_development
      hosts:
        # with docker
        - deendemy_db:27017
        # without docker
        # - 127.0.0.1:27017
      options:
        server_selection_timeout: 5
        # ssl: true
  options:
    app_name: DeendemyAPI

test:
  clients:
    default:
      database: deendemy_test
      hosts:
        # with docker
        - deendemy_db:27017 
        # without docker
        # - 127.0.0.1:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
  options:
    app_name: DeendemyTestAPI
