development:
  clients:
    default:
      database: deendemy_test
      hosts:
          - localhost:27017
      options:
        user: test
        password: test
        auth_source: admin
        server_selection_timeout: 5
        # ssl: true
  options:
    app_name: DeendemyAPI

test:
  clients:
    default:
      database: deendemy_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
  options:
    app_name: DeendemyAPI
