development:
  clients:
    default:
      uri: <%= ENV['MONGO_URI'] %>
      options:
        user: test
        password: test
        server_selection_timeout: 5
        # ssl: true
  options:
    app_name: DeendemyAPI

test:
  clients:
    default:
      uri: <%= ENV['MONGO_URI'] %>
      options:
        user: test
        password: test
        read:
          mode: :primary
        max_pool_size: 1
  options:
  app_name: DeendemyAPI
